### ISSUE TITLE
Tracking issue for TC39 process requirements

### ISSUE THREAD

**Issue by jamiebuilds** [bathos/proposal-string-cooked#3]
## Stage 1

- [ ] introduced to TC39
- [x] champions identified (@jamiebuilds )
- [x] initial explainer ([Explainer](https://github.com/bathos/proposal-string-cooked))

## Stage 2

- [ ] committee approval
- [x] spec text written
- [ ] spec reviewers selected

## Stage 3

- [ ] committee approval
- [ ] spec editor sign off
- [ ] spec reviewer sign off
- [ ] received developer/implementer feedback

## Stage 4

- [ ] committee approval
- [ ] implemented in two browsers
- [ ] write test262 tests
- [ ] merge test262 tests
- [ ] prepare ecma262 pr
- [ ] editor-approved ecma262 pr

**Comment by jamiebuilds** [comment]
Working on a presentation to bring this proposal to the October meeting: https://docs.google.com/presentation/d/1Au8FP1xTuXb52d6kG1fxX5Cxl3J-02h3FAaq8tMEtn8/edit?usp=sharing
